### ISSUE TITLE
Feature request: per-vertex width

### ISSUE THREAD

**Issue by Alloyed** [TannerRogalsky/polyline.lua#2]
So I'm using polyline.lua to recreate the trail effects described in this [blogpost](https://joostdevblog.blogspot.nl/2016/09/creating-crisper-special-effects-with.html) by the awesomenauts dev team (thanks btw).

Polyline is nice and flexible, but one thing I can't figure out how to do is get a tapering line, like so:

![trails - segments as particles](https://user-images.githubusercontent.com/137977/27210226-e11c8870-521e-11e7-9523-99408d72357e.gif)

My instinct is that this is something that should be happening inside of polyline, instead of by editing the output mesh, but any solution is cool by me

**Comment by TannerRogalsky** [comment]
You are right that this will be much easier to do by modifying the width passed to `renderEdge` as we build the line, rather than modifying the output mesh.

However, the goal of this project is to replicate Love's line rendering in Lua and, since Love doesn't provide this functionality, I don't think it should be provided here either.

I recommend that you fork this and change the calls to `renderEdge` to your liking. I think these lines should be the only things you need to change.
https://github.com/TannerRogalsky/polyline.lua/blob/master/polyline.lua#L220-L229
